application: schemaorgae
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /docs/schema_org_rdfa.html
  static_files: data/schema.rdfa
  upload: data/schema.rdfa
  application_readable: True

- url: /docs
  static_dir: docs

- url: /
  static_files: static/index.html
  upload: static/index.html
  application_readable: True

- url: /search_files
  static_dir: static/search_files

- url: /.*
  script: api.app



