#application: schemaorgae
#application: webschemas

#version: 1
#module: default
runtime: python27
api_version: 1
threadsafe: true
  
automatic_scaling: #Only applicable for appengine accounts with billing enabled
  min_idle_instances: 1

instance_class: F2

#basic_scaling:
#  max_instances: 3
#  idle_timeout: 10m

inbound_services:
- warmup

env_variables:
#  TARGETSITE: 'localhost'

  PRODSITEDEBUG: 'False'
  #CONFIGFILE: 'https://raw.githubusercontent.com/RichardWallis/datacommons/appupdate/schema/datacomconfig.json'
  CONFIGFILE: 'siteconfiglocation.json'
  FORCEINDEXPAGES: 'False'
  DEVELOPVERSION: 'True'
  MOREBLOCK: 'True'
  WARMUPSTATE: 'Auto' # 'Off', 'On', 'Auto' - Off for localhost, On elsewhere
  STAYINEXTENTION: 'False'
  PAGESTOREMODE: 'CLOUDSTORE' # 'INMEM' (In instance memory), 'NDBSHARED' (NDB shared - accross instances), 'CLOUDSTORE' (Cloudstorage files)
  EXAMPLESTOREMODE: 'INMEM' # 'INMEM', 'NDBSHARED'
  TIMESTAMPSTOREMODE: 'CLOUDSTORE' # 'INMEM', 'NDBSHARED', 'CLOUDSTORE' 
#  CACHE_CONTROL: 'public, max-age=600'
  CACHE_CONTROL: 'no-cache'
  SUBDOMAINS: 'False' #'False' no subdomains, 'True' for pending.schema.org, bib.schema.org etc. 

includes:
- site/handlers.yaml


libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
