#application: schemaorgae
#application: webschemas
application: sdo-fibodev

version: 1
runtime: python27
api_version: 1
#threadsafe: true
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: docs/favicon.ico
  upload: docs/favicon.ico
  mime_type: image/x-icon

- url: /docs/schema_org_rdfa.html
  static_files: data/schema.rdfa
  upload: data/schema.rdfa
  application_readable: True
  mime_type: text/html

- url: /docs/jsonldcontext.json.*
  script: sdoapp.app

- url: /docs/full.*.html
  script: sdoapp.app

- url: /docs/schemas.html
  script: sdoapp.app

- url: /docs/tree.json.*
  script: sdoapp.app

- url: /docs
  static_dir: docs

#- url: /
#  static_files: static/index.html
#  upload: static/index.html
#  application_readable: True

- url: /search_files
  static_dir: static/search_files

- url: /.*
  script: sdoapp.app



libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
