#application: schemaorgae
#application: webschemas

#version: 1
#module: default
runtime: python27
api_version: 1
threadsafe: true
  
automatic_scaling: #Only applicable for appengine accounts with billing enabled
  min_idle_instances: 1

instance_class: F2

#basic_scaling:
#  max_instances: 3
#  idle_timeout: 10m

inbound_services:
- warmup

env_variables:
#  TARGETSITE: 'localhost'
  PRODSITEDEBUG: 'False'
  WARMUPSTATE: 'Auto' # 'Off', 'On', 'Auto' - Off for localhost, On elsewhere
  STAYINEXTENTION: 'False'
  PAGESTOREMODE: 'CLOUDSTORE' # 'INMEM' (In instance memory), 'NDBSHARED' (NDB shared - accross instances), 'CLOUDSTORE' (Cloudstorage files)
  EXAMPLESTOREMODE: 'INMEM' # 'INMEM', 'NDBSHARED'
  TIMESTAMPSTOREMODE: 'CLOUDSTORE' # 'INMEM', 'NDBSHARED', 'CLOUDSTORE' 
#  CACHE_CONTROL: 'public, max-age=600'
  CACHE_CONTROL: 'no-cache'

handlers:

- url: /favicon.ico
  static_files: docs/favicon.ico
  upload: docs/favicon.ico
  application_readable: True
  mime_type: image/x-icon

- url: /robots.txt
  static_files: docs/robots-blockall.txt
  upload: docs/robots-blockall.txt
  application_readable: True
  mime_type: text/plain

# To avoid: "Could not guess mimetype for docs/schemaorg.owl.  Using application/octet-stream."
- url: /docs/schemaorg.owl
  static_files: docs/schemaorg.owl
  upload: docs/schemaorg.owl
  application_readable: True
  mime_type: application/rdf+xml

- url: /docs/schema_org_rdfa.html
  static_files: data/schema.rdfa
  upload: data/schema.rdfa
  application_readable: True
  mime_type: text/html

- url: /docs/jsonldcontext.json.*
  script: sdoapp.app

- url: /docs/full.*.html
  script: sdoapp.app

- url: /docs/schemas.html
  script: sdoapp.app

- url: /docs/developers.html
  script: sdoapp.app

- url: /docs/tree.json.*
  script: sdoapp.app

- url: /docs
  static_dir: docs
  application_readable: True

- url: /admin
  static_dir: admin
  application_readable: True

#- url: /
#  static_files: static/index.html
#  upload: static/index.html
#  application_readable: True

- url: /search_files
  static_dir: static/search_files

- url: /version/latest/.*
  script: sdoapp.app

- url: /(version/[^/]*/)$
  script: sdoapp.app

- url: /(version/([^/]*))$
  script: sdoapp.app

- url: /version/
  script: sdoapp.app

- url: /version/(.*/.*\.rdfa)
  mime_type: text/html
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.rdfa)
  application_readable: True

- url: /version/(.*/.*\.ttl)
  mime_type: application/x-turtle
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.ttl)
  application_readable: True

- url: /version/(.*/.*\.jsonld)
  mime_type: application/ld+json
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.jsonld)
  application_readable: True

- url: /version/(.*/.*\.rdf)
  mime_type: application/rdf+xml
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.rdf)
  application_readable: True
 
- url: /version/(.*/.*\.nt)
  mime_type: application/n-triples
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.nt)
  application_readable: True

- url: /version/(.*/.*\.nq)
  mime_type: application/n-quads
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.nq)
  application_readable: True

- url: /version/(.*/.*\.csv)
  mime_type: text/csv
  static_files: data/releases/\1
  upload: data/releases/(.*/.*\.csv)
  application_readable: True

- url: /version/*/*
  static_dir: data/releases/
  application_readable: True

- url: /.*
  script: sdoapp.app




libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
