application: schemaorgtest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html
  application_readable: True

- url: /.*
  script: api.app



