#!/usr/bin/env python
import sys
from rdflib import Graph
if __name__ == '__main__':

        g = Graph()
        p = Graph()
        u = str(sys.argv[1])
        g.parse(u, format='rdfa', pgraph=p)#, charset="utf8")
        print g.serialize(format="nt", encoding="utf-8")


#        print "URL: ",u
#        print "# errors: "
#        print p.serialize(format="nt")
#        print "# data: "
