source 'https://rubygems.org'

gem 'linkeddata'
gem 'json-ld-preloaded'
gem 'rspec'
gem 'rake'
gem 'nokogiri'
gem 'nokogumbo'
gem 'equivalent-xml'
gem 'rdf-rdfa', github: "ruby-rdf/rdf-rdfa", branch: "develop"

group :debug do
  gem 'byebug'
end
